### ISSUE TITLE
add %buyer% placeholder

### ISSUE THREAD

**Issue by amarcais53** [Maxlego08/zAuctionHouse-Discord#11]
EN
That could be cool if you can add the %buyer% placeholder to the bot to get the name of the buyer when a transaction is done

FR

Cela pourrait être cool si vous pouviez ajouter le palceholder %buyer% au bot pour obtenir le nom de l'acheteur lorsqu'une transaction est effectuée

**Comment by Maxlego08** [comment]
Le placeholder a été ajouté pour le footer et le header.
