### ISSUE TITLE
[BUG]: JDA instance initialization failed, possibly due to exceptions related to CacheFlags

### ISSUE THREAD

**Issue by jiajunmao** [Maxlego08/zAuctionHouse-Discord#2]
When handling event `onSell`, the plugin calls `plugin.getJda()`. However, I can confirm that the instance returned is `null`. I am taking a look and hopefully can get a PR up soon.

**Comment by Maxlego08** [comment]
Hello,

I just updated the plugin to add more information when there is an error. Please let me know if this is enough for you.

**Comment by jiajunmao** [comment]
Sry for the late reply lul some stuff was dragging me down. I checked it and it is related to JDA not having "GUILD_PRESENCES", "GUILD_VOICE_STATES" intents and somehow that interferes with cache flags (from my rough understanding from skimming through their wiki). Adding those two flags to config.json solves the problem but again that might raise security concerns as the bot shouldn't be asking for those two intents. I can do some fixes when I get some time.

**Comment by Maxlego08** [comment]
Okay, I'll leave it to you

**Comment by Maxlego08** [comment]
Fix
