### ISSUE TITLE
The format of the currency in discord could be the same as in the game

### ISSUE THREAD

**Issue by thiagogebrimm** [Maxlego08/zAuctionHouse-Discord#5]
In the game it is in front, in discord it is behind

![image](https://user-images.githubusercontent.com/75040244/138560590-4b01e2d7-1266-4ef4-ac5d-0b28b7977d21.png)

![image](https://user-images.githubusercontent.com/75040244/138560598-3a2aebb4-1d41-4e43-8863-c08effc05c06.png)

**Comment by alwyn974** [comment]
You need to change the format in the config file
`Player **%seller%** just added x%amount% %material% for **%price%%currency%**` 
to `Player **%seller%** just added x%amount% %material% for **%currency% %price%**`

**Comment by thiagogebrimm** [comment]
AAAA oks, thanks
